### ISSUE TITLE
Kernal Panic on Big Sur 11.2.3

### ISSUE THREAD

**Issue by AcidRain9** [chris1111/DWA-160Wireless-Utility#1]
I got a kernel panic after installing the DWA-160 Wireless Utility 

I followed the provided instructions and the video guide 

I booted into recovery and disabled csrutil, csrutil authenticated-root and gatekeeper (sudo spctl --master-disable) and also changed the value of csr-active-config to EF0F0000 in my config.plist

I followed the video and installed the DWA-160Wireless-Utility. allowed MediaTek Inc in security before rebooting 
But during reboot I got a kernel panic over and over again

Here's my wireless USB details
Vendor ID                : 0x0E8D (MediaTek Inc.)
Product ID               : 0x7610
Friendly Name         : 802.11ac Wireless LAN Card
MediaTek 802.11ac Wireless LAN Card - 2× WiFi

Here's my config file
[config.zip](https://github.com/chris1111/DWA-160Wireless-Utility/files/7193524/config.zip)

Here's my OpenCore logs 
[opencore-2021-09-20-074737.txt](https://github.com/chris1111/DWA-160Wireless-Utility/files/7193535/opencore-2021-09-20-074737.txt)
And here's the kernel panic file
[Kernel-2021-09-20-004815.zip](https://github.com/chris1111/DWA-160Wireless-Utility/files/7193536/Kernel-2021-09-20-004815.zip)

Is there any more info you need?

**Comment by chris1111** [comment]
Did you reset NVRAM? After changing the csr active config value, it must be done

**Comment by AcidRain9** [comment]
Yes, I did Infact cleared it, but I was still got the error. I ended up reinstalling macOS with csr-config set to FF0F0000 following [this](https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/post-issues.html#disabling-sip) after my installation completed and installing dwa-160 wireless utility resulted in same error. But this time I noticed something that could be causing this 

![IMG_1181](https://user-images.githubusercontent.com/26188786/134063131-3b6cb4d8-2514-4e3b-8780-9bf96cd10060.JPG)

No matter how many times I tried to disable it from recovery or  csr-active-config the Apple Internal never got disabled. I cleared my NVRAM cache multiple times but no effect, do you think this could be causing the issue? If so, do you have any suggestions can I try to solve it?

**Comment by chris1111** [comment]
If you use OpenCore simply use the csractive config value
 then reset nvram with the OC Tools / CleanNvram.efi
no need to using RecoveryHD with OC

**Comment by AcidRain9** [comment]
I installed macOS again with csractive config value set to EF0F0000 

![IMG_1187-min](https://user-images.githubusercontent.com/26188786/134084107-e92aa6ec-b7aa-47aa-b5ab-9bc3127dd1e1.JPG)

SIP is fully disabled, csrutil, csrutil authenticated-root and gatekeeper all are disabled

But I still got the same error even the third time 

![IMG_1188-min2](https://user-images.githubusercontent.com/26188786/134084464-add64faa-624d-43d1-935b-2873d586c95d.jpg)

Thank you for your support, is there anything else I can do about it?

**Comment by chris1111** [comment]
I think you need to Update BS to the latest 11.6 (20G165) before trying this utility

And my question is why using this if you use OC , this program here also using Mediatek driver  OC Injections
https://github.com/chris1111/D-LinkUtility-Package

**Comment by AcidRain9** [comment]
I didn't know about the other utility, I came here from the [insanelymac ](https://www.insanelymac.com/forum/topic/299948-usb-wifi-updated-ralinkmediatek-rt2870-rt2770-rt3x7x-rt537x-rt5572/page/20/)forum and mostlyDWA-160Wireless-Utility is mentioned there. I will give the other utility a try and if it doesn't work I'll switch to macOS big sur 11.5+

**Comment by AcidRain9** [comment]
Following your suggestion I installed https://github.com/chris1111/D-LinkUtility-Package, I chose the opencore during installation and it installed without any problems I followed the video guide. I connected the wifi device before reboot, but even after reboot it wasn't reconnected to the wifi. How can I check if my device was connected? or if it's recognized by the macOS?
